# Explore data

data contains 3 classes of data:
    + edges (graph)
    + loc
    + vel

In [86]:
import numpy as np

suffix = "_springs5"

loc_train = np.load('loc_train' + suffix + '.npy')
vel_train = np.load('vel_train' + suffix + '.npy')
edges_train = np.load('edges_train' + suffix + '.npy')

In [87]:
### 2: ball move in 2-d space; simluation returns a 2-d coordinates

loc_train # `(n_sim, time steps, 2, n_balls)`
vel_train # `(n_sim, time steps, 2, n_balls)`

edges_train # `(n_sim, n_balls, n_balls)`


array([[[0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 1., 0.],
        [0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 1.],
        [1., 0., 1., 1., 1.],
        [0., 1., 0., 1., 0.],
        [0., 1., 1., 0., 1.],
        [1., 1., 0., 1., 0.]],

       [[0., 0., 1., 1., 1.],
        [0., 0., 1., 0., 1.],
        [1., 1., 0., 1., 0.],
        [1., 0., 1., 0., 0.],
        [1., 1., 0., 0., 0.]],

       ...,

       [[0., 0., 1., 0., 1.],
        [0., 0., 1., 1., 0.],
        [1., 1., 0., 0., 0.],
        [0., 1., 0., 0., 1.],
        [1., 0., 0., 1., 0.]],

       [[0., 0., 1., 0., 0.],
        [0., 0., 1., 1., 0.],
        [1., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1.],
        [0., 0., 1., 1., 0.],
        [0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [1., 0., 0., 0., 0.]]])

a simulation -> a ball connection status over all time prioed

![img](https://github.com/ethanfetaya/NRI/blob/master/nri.png)


# process edges

In [88]:
print(edges_train.shape)
print(edges_train[0,:])
num_atoms = edges_train.shape[1]
edges_train_ori_true = edges_train

(500, 5, 5)
[[0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]]


In [89]:
## reshape, all element flatten
edges_train = np.reshape(edges_train, [-1, num_atoms ** 2])
print(edges_train.shape)

(500, 25)


In [90]:
edges_train = np.array((edges_train + 1) / 2, dtype=np.int64)




In [91]:
off_diag_idx = np.ravel_multi_index(
    np.where(np.ones((num_atoms, num_atoms)) - np.eye(num_atoms)),
    [num_atoms, num_atoms])

In [92]:
edges_train = edges_train[:, off_diag_idx]

In [93]:
print(edges_train.shape)

(500, 20)


In [97]:
def add_diag(edges_train_single):
    '''
    edges_train_single: (20, ) nparray
    '''
    diag_idx = np.ravel_multi_index(np.where( np.eye(num_atoms)),[num_atoms, num_atoms])
    
    added = np.insert(edges_train_single, diag_idx - range(0, diag_idx.shape[0]), 0, axis=0).reshape(num_atoms,num_atoms)

    return added

In [99]:
edges_ori_reconst = np.apply_along_axis(add_diag, 1, edges_train)

In [100]:

print(edges_ori_reconst.shape)

(500, 5, 5)
